### ISSUE TITLE
`pin!` ignores GC

### ISSUE THREAD

**Issue by vchuravy** [lcw/Heptapus.jl#9]
`pointer(a)` loses the GC reference to `a` and therefore the created HostBuffer doesn't hold a reference to `a`.
Also it seems like the return value of `pin!` is ignored in the caller and thus the GC is free to remove the HostBuffer and run
the finalizer on it.

https://github.com/lcw/Heptapus.jl/blob/0f235861c201cbfdcfc4368629e1dccda3868b57/examples/mpicuda/try.jl#L6

**Comment by lcw** [comment]
I think I am missing something.  I agree that the `HostBuffer` doesn't hold a reference to `a`.  However, `a` is the object that I keep and is used to get the pointer to pass to the copy functions.  I figured, possibly incorrectly, the `HostBuffer` would be captured by the `finalizer` and thus not available to be garbage collected until `a` was freed.

**Comment by vchuravy** [comment]
Ah! I didn't see the `finalizer(_ -> Mem.unregister(ad), a)` e.g. that it was captured by the finalizer. So yeah as long as you can rely on your user not losing a reference to `a`, this is fine.
